FROM node:14-slim

ARG INSTALL_PATH=/opt/mcsm
ARG JDK_VERSION

# install git & openjdk
# add bullseye repo for openjdk-17, stretch repo for openjdk-8, openjdk-11 is already included in default buster repo
RUN echo "deb http://deb.debian.org/debian bullseye main" >> /etc/apt/sources.list && \
    echo "deb http://deb.debian.org/debian stretch main" >> /etc/apt/sources.list && \
    apt update && \
    apt install -y git openjdk-$JDK_VERSION-jre-headless

# install mcsm
RUN git clone https://github.com/MCSManager/MCSManager-Daemon-Production $INSTALL_PATH/daemon && \
    cd $INSTALL_PATH/daemon && \
    npm i --production

ENV TZ=Asia/Shanghai
ENV PUID=0
ENV PGID=0
ENV UMASK=022
VOLUME [ "$INSTALL_PATH/daemon/data", "$INSTALL_PATH/daemon/logs" ]
EXPOSE 24444 25565-25575
WORKDIR $INSTALL_PATH/daemon
CMD [ "node", "app.js" ]
